name: 'Technical Lag Calculator'
description: 'Calculates the technical lag of the given package manager files.'
inputs: 
  inputPath:
    description: 'Path to the package manager files to analyze, relative to the repository root.'
    default: ''
    required: true
  outputPath:
    description: 'Path to store the generated artifacts.'
    default: 'statistics'
    required: true
  analyzeSubDirs:
    default: 'false'
    required: true
    description: 'If set to true we analyze all package.json files found in the inputPath and its subdirectories.'
outputs:
  results:
    description: 'The analysis results.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.inputPath}}
    - ${{ inputs.outputPath}}