on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Output build artifacts to /github/workspace on the container.
      - name: Execute technical lag calculator
        uses: ./
        id: techlag
        with:
          inputPath: examples
          outputPath: statistics

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: technical_lag_artifacts
          path: ${{ github.workspace }}/statistics
